# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-1)
# Generated by Django 6.0.6 on 2026-07-03 17:37

# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 3-3)
import django.db.models.deletion
import uuid
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 5-5)
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 14-15)
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 20-20)
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 23-23)
                ('name', models.CharField(choices=[('SCIENCE', 'Science'), ('COMMERCE', 'Commerce'), ('HUMANITIES', 'Humanities')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 26-26)
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 30-30)
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 33-33)
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 35-36)
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.school')),
            ],
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 38-40)
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 48-51)
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 60-63)
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.grade')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.stream')),
            ],
        ),
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 67-67)
            name='StudentSubjectEnrollment',
            fields=[
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 69-73)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 83-96)
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.teacherprofile')),
            ],
        ),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 99-114)
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('grade', 'roll_number'), name='unique_roll_number_per_grade'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('grade', 'subject_code')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectenrollment',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together={('teacher', 'grade', 'subject')},
        ),
    ]
