# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-18)
# Generated by Django 6.0.6 on 2026-07-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], db_index=True, max_length=20),
        ),
    ]
