# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-40)
# Generated by Django 6.0.6 on 2026-07-03 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PUBLISH', 'Publish'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SUBMIT', 'Submit'), ('VIEW', 'View'), ('START', 'Start'), ('COMPLETE', 'Complete'), ('DOWNLOAD', 'Download')], db_index=True, max_length=20)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='audit_logs__school__62c9e7_idx'), models.Index(fields=['user', '-created_at'], name='audit_logs__user_id_c41764_idx'), models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs__content_9ccfc6_idx')],
            },
        ),
    ]
