# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-1)
# Generated by Django 6.0.6 on 2026-07-03 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 14-16)
        ('academics', '0001_initial'),
        ('content_management', '0001_initial'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=255)),
                ('homework_questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 28-29)
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='content_management.module')),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 33-33)
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homework_management.homeworkrepository')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework_submissions/')),
                ('marks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUBMITTED', 'SUBMITTED'), ('GRADED', 'GRADED')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 57-57)
                ('feedback', models.TextField(blank=True, default='')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework_management.homeworkrepository')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 62-62)
                'indexes': [models.Index(fields=['student', 'status'], name='homework_ma_student_c52ede_idx')],
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
