# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-1)
# Generated by Django 6.0.6 on 2026-07-03 17:37

import django.db.models.deletion
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 4-4)
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 14-14)
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 20-20)
            name='Chapter',
            fields=[
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 22-29)
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('chapter_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.subject')),
            ],
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 31-33)
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 36-36)
            name='Module',
            fields=[
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 38-46)
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('module_number', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content_management.chapter')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 49-49)
                'ordering': ['module_number'],
            },
        ),
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 53-53)
            name='LessonContent',
            fields=[
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 55-55)
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 57-59)
                ('content', models.JSONField()),
                ('extra_notes', models.JSONField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lesson_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 61-63)
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='content_management.module')),
            ],
            options={
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 66-66)
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 70-70)
            name='LessonCompletion',
            fields=[
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 72-77)
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_started', models.BooleanField(db_index=True, default=False)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 79-81)
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='content_management.module')),
            ],
        ),
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 85-101)
            name='ModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('lessons_viewed', models.PositiveIntegerField(default=0)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content_management.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 104-108)
                ('completed_lessons', models.IntegerField(default=0)),
                ('pending_lessons', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 111-151)
        migrations.CreateModel(
            name='TeacherDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_published', models.IntegerField(default=0)),
                ('students_impacted', models.IntegerField(default=0)),
                ('average_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['grade', 'subject'], name='content_man_grade_i_b1d71b_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('grade', 'subject', 'chapter_number'), name='unique_chapter_per_subject'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['chapter', 'is_published'], name='content_man_chapter_5527e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('chapter', 'module_number'), name='unique_module_per_chapter'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['student', 'is_completed'], name='content_man_student_d4e849_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncompletion',
            index=models.Index(fields=['module', 'is_completed'], name='content_man_module__175214_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessoncompletion',
            constraint=models.UniqueConstraint(fields=('student', 'module'), name='unique_student_module_progress'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('student', 'module')},
        ),
    ]
