# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-1)
# Generated by Django 6.0.6 on 2026-07-03 17:37

# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 3-3)
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 11-11)
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 16-16)
            name='ClassAnalytics',
            fields=[
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 18-37)
                ('class_analytics_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_period', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_students', models.IntegerField(default=0)),
                ('total_assessments', models.IntegerField(default=0)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastPerformanceHistory',
            fields=[
                ('past_performance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('performance_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 39-98)
            ],
        ),
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('performance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('modules_completed', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('homework_completed', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ResultReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('student_analytics_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_period', models.DateTimeField(auto_now_add=True)),
                ('past_performances', models.JSONField(default=dict)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('highest_score', models.IntegerField(default=0)),
                ('lowest_score', models.IntegerField(default=0)),
                ('improvement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_assessments', models.IntegerField(default=0)),
                ('total_modules_completed', models.IntegerField(default=0)),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_homework_completed', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('homework_submission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_tests', models.IntegerField(default=0)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
