# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-265)
# Generated by Django 6.0.6 on 2026-07-03 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('analytics_performance', '0001_initial'),
        ('assessment_management', '0001_initial'),
        ('content_management', '0001_initial'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classanalytics',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_management.assessment'),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.module'),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.teacherprofile'),
        ),
        migrations.AddField(
            model_name='classdashboard',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='classdashboard',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='classdashboard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_management.assessment'),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.chapter'),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.module'),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='performancehistory',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_management.assessment'),
        ),
        migrations.AddField(
            model_name='performancehistory',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.module'),
        ),
        migrations.AddField(
            model_name='performancehistory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='performancehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancehistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_performance.performancehistory'),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_management.assessment'),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.chapter'),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.module'),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='performancehistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='analytics_performance.resultreport'),
        ),
        migrations.AddField(
            model_name='pastperformancehistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_performance.resultreport'),
        ),
        migrations.AddField(
            model_name='classanalytics',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_performance.resultreport'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_management.assessment'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.chapter'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.module'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_performance.performancehistory'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectdashboard',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentsubjectdashboard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectdashboard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='classdashboard',
            unique_together={('grade', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectdashboard',
            unique_together={('student', 'subject')},
        ),
    ]
