# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 1-1)
# Generated by Django 6.0.6 on 2026-07-03 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 14-15)
        ('content_management', '0001_initial'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_questions', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='content_management.module')),
            ],
        ),
        migrations.CreateModel(
            name='MCQPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(max_length=1)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_pool', to='content_management.module')),
            ],
        ),
        migrations.CreateModel(
            name='MCQBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='assessment_management.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_batches', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='assessment_management.mcqpool')),
            ],
            options={
                'unique_together': {('assessment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField()),
                ('score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='assessment_management.mcqbatch')),
            ],
        ),
# >>> CHANGED in commit 47214f0 — Fix user authentication, add school assignment, and update gitignore (lines 68-86)
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment_management.assessment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='assessment_management.studentattempt')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'assessment'], name='assessment__student_e530ec_idx')],
            },
        ),
    ]
